### ISSUE TITLE
Unable to open 'DRR Word Template.docx' file in common folder

### ISSUE THREAD

**Issue by hmthomas** [nationalparkservice/IMD_DRR_Template#14]
We would like to have a look at this template, but the error below appears upon opening.

![image](https://user-images.githubusercontent.com/6645997/139171181-92077cf1-1953-43c9-a269-2e107d7398d8.png)

Clicking yes to recover generates another error.

![image](https://user-images.githubusercontent.com/6645997/139172099-db32711e-413d-427e-a32e-790c8ee4d86f.png)

We tried some additional recovery options but nothing worked.

**Comment by joe-devivo** [comment]
This has been removed.
