### ISSUE TITLE
Suggested edits to vignettes

### ISSUE THREAD

**Issue by llnelson** [nationalparkservice/IMD_DRR_Template#3]
[PurposeAndScope](https://htmlpreview.github.io/?https://github.com/nationalparkservice/IMD_DRR_Template/blob/master/vignettes/PurposeAndScope.html):  

- Spell out 'DOI'.
- Replace 'journals' with 'data journals in 'external peer-reviewed scientific journals' phrase (P2, Background)
- Change 'required' to 'mandated' in 'Note that publication in a data release report series (not required)...' (P3, Background)
- Under 2 Definitions: are there citations for any of these?
- Add definitions for Quality Assurance and Quality Control
- In section 3.1, add links to documents if available
- Ditto for section 3.2 and 3.3
- In section 3.3, is a word missing before or after 'data'? (1st sentence under IMD Reporting and Analysis Guidance)
- In section 4, add a link to the FAIR website

**Comment by llnelson** [comment]
[DRR Outline and Content Guide](https://htmlpreview.github.io/?https://github.com/nationalparkservice/IMD_DRR_Template/blob/master/DRR_Template.html): 

- Section 4: DQE  Fix misspelling of 'intendend'
- Section 4: Regarding 'patterns in data that do not meet established standards or data quality objectives', does this imply an EDA level 0 summary of the dataset structure?
- Section 8: Change section title to 'Code Listing' since we use non-R languages in the Program
- Ditto for Section 9

Question re: section 8 - Add a statement to specify the intent that this section includes both the report formatting and the data processing content (i.e. the RMD or IPYNB contains all processing code)?

**Comment by llnelson** [comment]
[How to Use the DRR Template](https://htmlpreview.github.io/?https://github.com/nationalparkservice/IMD_DRR_Template/blob/master/vignettes/HowToUseThisTemplate.html):  

- Do DRRs include the code for redacting/fuzzing (etc.) of protected data?  Hmm...  Perhaps a section on DRRs for protected vs. not protected data is needed.
- Until we have a robust GitHub Enterprise option and have set up our desired Science Branch publication structure, I would not recommend the first approach under section 2 Project Setup.

Expect further comments since I've not tried using the workflow suggested in this vignette...

**Comment by llnelson** [comment]
[Creating Data Packages](https://htmlpreview.github.io/?https://github.com/nationalparkservice/IMD_DRR_Template/blob/master/vignettes/CreatingDataPackages.html): 

- Step 3: Change 'Create the CSV' file to 'Create the Delimited File'.  As we proceed with dataset production, most of our tabular outputs will be tab-delimited, not comma-delimited since the latter is challenging to produce and use. 
-Step 5: Create the Attributes Table section - suggest including a recommendation of using GMT if datetime content is used
-Step 6: Create Category Variables Table - add a tab-delimited file containing the values in Table 4 to the [data_objects](https://github.com/nationalparkservice/IMD_DRR_Template/tree/master/dataPackages/DataPackageTemplate/data_objects) folder. 
- Step 7: Correct title to Set Geographic Coverage
- Step 7: EML has a robust structure for documenting spatial data. Two things: 
-- 'Coverage' implies bounding extent, not actual geography elements, so I don't agree with replication of coordinate values for point data within this section - those should be reflected in geometry objects in [eml-spatialVector section](https://nceas.github.io/eml/images/eml-spatialVector.png) of the eml file assuming we intend to include them.  
-- Spatial reference must be included i.e. NAD2011 Geographic, UTM Zone 12N NAD83, etc.) and the eml-spatialVector section includes elements for this.

**Comment by joe-devivo** [comment]
made several changes based on comments. we can talk about the ones I did not change. 
In general I'm staying away from providing any guidance on data standards or related to other policies with this guidance b/c it may be used by others outside IMD (like other series) and may change.

**Comment by llnelson** [comment]
One point on defining QA and QC - it seems the [How to Use vignette](https://htmlpreview.github.io/?https://github.com/nationalparkservice/IMD_DRR_Template/blob/master/vignettes/HowToUseThisTemplate.html) is the appropriate place for those definitions.  I concur with the approach to emphasize comparison to quality standards and think clear definitions of QA and QC in this vignette help emphasize both the distinction between quality standard checks and QA QC operations which are implied and sometimes documented by other DRR components.
