### ISSUE TITLE
setwd() prevents Rmd from knitting

### ISSUE THREAD

**Issue by wright13** [nationalparkservice/IMD_DRR_Template#5]
Line 146

**Comment by joe-devivo** [comment]
I think the problem is that you need to specify the projectDir in line 3 of the template, and the knitting bombs out if the directory doesn't exist. I've added in an annotation to that line that this needs to be updated prior to knitting, but if you could please verify that'd be great.

**Comment by wright13** [comment]
Oops, sure enough. Totally missed that. It works now!
